apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
spec:
  containers:
    - name: test-container
      image: alpine:latest2
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "$(date) - Hello World Again!!!"; sleep 30; done
